# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gamebook.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bouttonCommencer = QtWidgets.QPushButton(self.centralwidget)
        self.bouttonCommencer.setObjectName("bouttonCommencer")
        self.verticalLayout_4.addWidget(self.bouttonCommencer)
        self.bouttonSauver = QtWidgets.QPushButton(self.centralwidget)
        self.bouttonSauver.setObjectName("bouttonSauver")
        self.verticalLayout_4.addWidget(self.bouttonSauver)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.textChapitre = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textChapitre.sizePolicy().hasHeightForWidth())
        self.textChapitre.setSizePolicy(sizePolicy)
        self.textChapitre.setObjectName("textChapitre")
        self.verticalLayout_5.addWidget(self.textChapitre)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.choix1 = QtWidgets.QRadioButton(self.centralwidget)
        self.choix1.setObjectName("choix1")
        self.verticalLayout_6.addWidget(self.choix1)
        self.choix2 = QtWidgets.QRadioButton(self.centralwidget)
        self.choix2.setObjectName("choix2")
        self.verticalLayout_6.addWidget(self.choix2)
        self.choix3 = QtWidgets.QRadioButton(self.centralwidget)
        self.choix3.setObjectName("choix3")
        self.verticalLayout_6.addWidget(self.choix3)
        self.boutonContinuer = QtWidgets.QPushButton(self.centralwidget)
        self.boutonContinuer.setObjectName("boutonContinuer")
        self.verticalLayout_6.addWidget(self.boutonContinuer)
        self.verticalLayout.addLayout(self.verticalLayout_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.boutonContinuer.clicked.connect(MainWindow.continuer) # type: ignore
        self.bouttonCommencer.clicked.connect(MainWindow.commencer) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bouttonCommencer.setText(_translate("MainWindow", "Commencer"))
        self.bouttonSauver.setText(_translate("MainWindow", "Sauvegarder"))
        self.choix1.setText(_translate("MainWindow", "choix1"))
        self.choix2.setText(_translate("MainWindow", "choix2"))
        self.choix3.setText(_translate("MainWindow", "choix3"))
        self.boutonContinuer.setText(_translate("MainWindow", "Continuer"))
